name: Test

on:
  workflow_dispatch:
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: echo workspace
        run: echo $GITHUB_WORKSPACE
        shell: bash

      - name: Install nginx
        run: sudo apt-get install nginx -y
      - name: check nginx config
        run: echo "127.0.0.1 crud-backend" | sudo tee -a /etc/hosts && sudo cp /home/runner/work/sre-hw19/sre-hw19/nginx-todo-crud/conf /etc/nginx/conf.d/default.conf && sudo nginx -t

      - name: Install requirements
        run: pip install -r flask-sqlite3-todo-crud/requirements.txt
      - name: Run tests
        run: coverage run flask-sqlite3-todo-crud/test.py
      - name: Tests report
        run: coverage report


